//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//
//  Template generated by Tambanco
//

import Foundation

// MARK: Output protocol
protocol ___VARIABLE_productName:identifier___ViewProtocol: AnyObject {

}

// MARK: Input protocol
protocol ___VARIABLE_productName:identifier___PresenterProtocol: AnyObject {
    init(view: ___VARIABLE_productName:identifier___ViewProtocol, model:  ___VARIABLE_productName:identifier___Model)

}

class ___FILEBASENAMEASIDENTIFIER___: ___VARIABLE_productName:identifier___PresenterProtocol {

    weak var view: ___VARIABLE_productName:identifier___ViewProtocol?
    var model: ___VARIABLE_productName:identifier___Model
    
    // Enter buisness logic here
    
    required init(view: ___VARIABLE_productName:identifier___ViewProtocol, model: ___VARIABLE_productName:identifier___Model) {
        self.view = view
        self.model = model
    }
}
