//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//
//  Template generated by Tambanco
//

import UIKit

class ___VARIABLE_productName:identifier___ViewController: UIViewController {

	var presenter: ___VARIABLE_productName:identifier___PresenterProtocol!

	override func viewDidLoad() {
        super.viewDidLoad()
        
    }
}

// MARK: - Binding
extension ___VARIABLE_productName:identifier___ViewController: ___VARIABLE_productName:identifier___ViewProtocol {
    
}
