//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//
//  Template generated by Tambanco
//

import Foundation

struct ___FILEBASENAMEASIDENTIFIER___ {
    
}
